app:
   name: corporation-api
   version: 1.0

logger:
  log_level: debug

queue_config:
   region: ap-northeast-1
   url: https://sqs.ap-northeast-1.amazonaws.com/993928368265/CorporationQueue.fifo
   endpoint: https://sqs.ap-northeast-1.amazonaws.com
